# Generated by Django 2.0.6 on 2018-06-29 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='设备名')),
                ('s_num', models.CharField(max_length=10, verbose_name='设备号')),
                ('z_num', models.CharField(max_length=12, verbose_name='资产号')),
                ('date_in', models.DateField(verbose_name='入库日期')),
                ('date_out', models.DateField(verbose_name='出库日期')),
                ('memo', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='耗材名')),
                ('date_in', models.DateField(verbose_name='入库日期')),
                ('date_out', models.DateField(verbose_name='出库日期')),
            ],
            options={
                'verbose_name': '耗材',
                'verbose_name_plural': '耗材',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='合同名')),
                ('company', models.CharField(max_length=50, verbose_name='供应商')),
                ('date', models.DateField(verbose_name='签订日期')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='部门编号')),
                ('name', models.CharField(max_length=30, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='付款日期')),
                ('percentage', models.PositiveIntegerField(verbose_name='付款百分比')),
                ('sum', models.PositiveIntegerField(verbose_name='付款金额')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '付款',
                'verbose_name_plural': '付款',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('number', models.CharField(max_length=10, verbose_name='员工号')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
        migrations.AddField(
            model_name='consumable',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Contract', verbose_name='合同'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Staff', verbose_name='领用人'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='asset',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Contract', verbose_name='合同'),
        ),
        migrations.AddField(
            model_name='asset',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Staff', verbose_name='使用人'),
        ),
    ]
